---
version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-79
ratings:
  paths:
    - Gemfile.lock
    - "**.rb"
exclude_paths:
  - spec/
  - vendor/
