require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7

Layout/EndOfLine:
  EnforcedStyle: lf

Lint/AmbiguousBlockAssociation:
  Enabled: false # This is broken in Rubocop 0.48

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "spec/**/*.rb"

Metrics/ClassLength:
  Exclude:
    - "lib/url_validation.rb"

Layout/LineLength:
  Max: 160 # 80*2 - you have a widescreen monitor, right?

# It's asinine that a single Hash parameter is OK but kwargs aren't, when kwargs are an order
# of magnitude faster, easier to statically analyze and document, and arguably easier to grok.
Metrics/ParameterLists:
  CountKeywordArgs: false

# It's named this way because we had to rename the gem.
Naming/FileName:
  Exclude:
    - "lib/art19-url_validation.rb"

RSpec/NestedGroups:
  Max: 4

# Re-enable this when the following is resolved:
# https://github.com/rubocop-hq/rubocop/issues/5953
# module_function is a false positive as are attr_accessor
# and friends. WTF, rubocop people?
Style/AccessModifierDeclarations:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    "%i": "[]"
    "%I": "[]"
    "%r": "{}"
    "%w": "[]"
    "%W": "[]"

Layout/HashAlignment:
  Enabled: true
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table
