language: ruby
dist: bionic
env:
  global:
    - secure: TtRuZvlAm4Kkk4lIGD5am2r0vZESp7sTmikBATUYB80uQiTr73LtMc/WVg5Vn2ImFH6EUFdUxMFQCwLsV0Hjak+TsYeMZtPFhWjLMbGpoNjbdxcfVyoY4aNnUpejHQ0fhv5yE9+w/zGPaI+vr0LJAlRqAivCWN1D0X4bFVUkmeQyVuQ1LOdHD1oNQWmDHiNoVvVIFyQFaECqtNXZZ2sqn+f5j055hOP0aPD31ZBPVrM8NdjKxDVtXIcMKUanLu8t98pgNe6MSBooBMmno9zNZP2h+SV3YPr6XIdF/QYzIsWqYWqqE6d1typGrcGTJJMb2cD2E0TU8aKt/a/LCWhR4rcRq1MK1LrreJk1MgsTylpmnvLXXynDWaXj1ITbbJDlLecJXgBbuBv5tDOOe2TUR441ru1O0efDE8K3uUFNTJzzrST6NCXJ4BP3ZgBag7dowTjQDERQoSVO7eR9JVtAyvdDw9w3sKo+vFwySOgbgQ5T6hY6C2bbUpBaVH8kq+zkF3Y+AYUn+fJaRMtoJdXB8f7UPBJ06m/AZIc+ErCF5tmbF1YtoN0UozX1nBPUVlz0UUOUZsFh+WZ+pto/GI3dFXbCeFlKI3fK64SQH6gAVA4qaeSXtTL6Ez4fnktUnrVKauEk92MrcfD1UrNJxCHXnPs0e/fA6sN0zoHmg0qHing=
rvm:
- 2.6.2
- 2.7.1
cache:
  bundler: true
notifications:
  slack:
    secure: yshPGE4rTSGlLR7s7lhyvN33gt/5KDpjac63Qor7lxO/dcgOg844sKCOkndsQZAFJqB3LkhMGSOxW+CRQhJrdB3327f9fYq3G3W7meb37nU1l830EN1IjAtKzAgbH1o2sofDgXwuMK+ZWVInChmj/SVDCm0yMhOsQoiCZDWxO0fhUzFa7id5G8KPbNm+viF4kWmjyytWYHpubjzR5nJuzwvtPU0F/QytbYQ3X/FznxnTAdDOxw70J2R/TRHjbY+NpYcrLMRWOgXAde6p1LX5HuV6wFKrKgf417f6H9UaNmFb5G0cyQECFP+cdB/uTmU2I9g9IqDmW8A0wYit56Fd1WEL3GkRYE4Tg0X5IynPAZtS7hanQevETOJfAY8g6Dx0Ovwq1VL0zAIeCnt4UKQ4UWwRhF0U0DYuSC/rWM909LyEeP4zoENJMW67CYwS/HM2+kkP890dEIpsYLbYzzkyLT+XBx8900VU3yT+MtOPtj1q/NHAcRPdg4NT3GjLkQVdJpvO0QLC2F7IVN49/naQcLPkWz0X4tK/HCYN3wFcvw4gyN1lIw2dDV9E81cC1e5+SHq0cWWNVQegsL2Ke8Ceb+xHsUyKcUVBItJsj5TjIPfdoE2D1jprZsQeuuWeEWq+fXT5g0WiN+Z4emaG8XG/wFKifJEXhQLam5z9wLoaltY=
before_install:
  - gem install bundler
  - bundle --version
before_script:
  - echo -e "build ruby version $TRAVIS_RUBY_VERSION"
  - if [ "$TRAVIS_RUBY_VERSION" = "2.6.2" ]; then export COVERAGE=true; fi
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ~/cc-test-reporter && chmod +x ~/cc-test-reporter
  - if [ "x$COVERAGE" = "xtrue" ]; then ~/cc-test-reporter before-build; fi
script: bundle exec rspec
after_script:
  - if [ "x$COVERAGE" = "xtrue" ]; then ~/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
