language: ruby
dist: bionic
env:
  global:
    - secure: alwrmzNoUiFy384qcfoA6x41InPy/f8VeKZlqTSiTukY6rkbXjd6cLNT6y6eTNDTR3bqPSawWeTJbCmvcScDcukne9wUfcwPqb3jheuRH9w2FIT/iBm+R4HX++LsVQtDdwUrSzJTNPSykqNZHnlbC7GTMGtarHRQAashtsHR2HbBdOFRkYgfpTBxKMEGtFf/k5sNOBApfGS4gv5J9Qhg+tU7bmTfhttjatG+Nict0sp06clJRTUXKIM6eUCoBiEG8gdMfovtJ4SjgndUEr4yI+atZJL0L1Eu55yNmVKWRABO8ILL5CtdHlHjCbi+2OvdvFijAFvuP3HgI6DTy6fkA1MwQLlncKWkQGvJEW2KM6UhUsemdbLiaspYrZRXjf/HoM+mmWmRzlHgO1QtuPwtFrTS+6DOylcuUg2NeVvg14pHoBqspNV2+r5PU/5Jvo2g/cDVp0H7CQ764xIOJuY/XB0HInmOmNKp+jl2qgazm4/g4Txd/YuhXKP3Cps91BbwwR5OsaOHKqusriuUljwvxU6XU7LezAizj8HVE4L7U9fYlPER3bxA9IHS9tHTb3iPTsvbSMdvI42Q0mKQEAt8W5D5t6/REoqETmNsJ+Ez7yhIB4S0abGsKIUkevpRz8i80FKFd0W5R2x5cj9ZYCtscXko67WUnkGgUmfUxel3XCs=
rvm:
- 2.6.2
- 2.7.1
cache:
  bundler: true
notifications:
  slack:
    secure: PMldiCSD2At8hh3/HwLg4rzczr9nPhAfcUO5msTm8/+1vOFvY8tEUqm7Ny84wv635X/Dhuk+YUd1MjfN72NG29N9RzJzEpWoQn2MHk83HflkhxPmr6kKOqeir1FnPb+X9pzJBatuz0PWd27QqEXjWIDdiGxs2udwtXpUGEKVLOfaqhYilbkDF96NCu3vZjdWBHAzP5x2lHEXs+meEkZ9P6iN89E//IpgAz6pbmA8oAgyW9UdIAWXEsjSmKGYja1dyPtYC/2Hu0P+1wB9qPZ9CsiA/r1ja7uRncOrst29My9K1aujY1BDIGCWHhcCddFu7ZYpDaDt26vQ4ZmNiFzh4/4nIswLlHyq5A4OKTxbFSVt0OG5BDLMKfl8nS+h28HeaS5VdOcu2aRI1TTkmeUSvVKejJ1IgWzROaACFy4YRD67r5d9l9yXMlU75yX90x+1UbF2nZC9ndsEDAjhiOWv59bUNJR0GnqEaUXO/OylBxUPJtdTRL4l10GFDZ1kV8eX/adIi12dwMyJwLFKLrjFX3dSvVgRwrGzhffoT67FvsTmlRoOEugkF6uP+o9y3ruKETaSx59/5yaXfKwEsXAaUAPOschjKQ+pKRYSDWCdBjWfVQU/9+zscQ3b1ihs1iyQwDIlbZdcolCknxkmn5MzzKqJXgGZDaLBaG5l2SGJ5M0=
before_install:
  - gem install bundler
  - bundle --version
before_script:
  - echo -e "build ruby version $TRAVIS_RUBY_VERSION"
  - if [ "$TRAVIS_RUBY_VERSION" = "2.6.2" ]; then export COVERAGE=true; fi
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ~/cc-test-reporter && chmod +x ~/cc-test-reporter
  - if [ "x$COVERAGE" = "xtrue" ]; then ~/cc-test-reporter before-build; fi
script: bundle exec rspec
after_script:
  - if [ "x$COVERAGE" = "xtrue" ]; then ~/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
